In [1]:
import numpy as np

# Broadcasting

### <span style="color:blue">**1. Broadcasting Intro**</span>

In [5]:
#binary operation is conducted between two arrays of same size
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

print("Array a : " + str(a))
print("Array b : " + str(b))
print("Array a + b : " + str(a + b))

Array a : [0 1 2]
Array b : [5 5 5]
Array a + b : [5 6 7]


In [6]:
#Addition between a scalar and a 1 by 3 array
a + 5

array([5, 6, 7])

In [8]:
#addition between a (3, 3) array and a (1, 3 array)
Mat = np.ones((3, 3))
display(Mat)
display(a)

#the one-dimensional vector will be broadcasted to match the dimension of the two-dimensional array
display(Mat + a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [9]:
#addition between (1, 3) array and (3, 1) array
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

display(a)
display(b)

display(a + b)

array([0, 1, 2])

array([[0],
       [1],
       [2]])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### <span style="color:blue">**2. Broadcasting Rules**</span>

1. If the dimension of two arrays are different, the array with smaller dimension will be reshaped so that their dimensions match. If the size of the smaller array was (6,), always add 1 in the first position of the size so that the array reshapes to (1,6)
<br>
<br>
2. In a given dimension, if the size of two arrays do not match, increase the size of the matrix with 1 to match the size of the other array. For example, if array A's size is (6,6) and array B's size is (1,6), reshape array B to (6,6)
<br>
<br>
3. In a given dimension, if the size of the two arrays do not match, or if none of the array's size is 1, you will get an error

In [13]:
a = np.ones((2, 3))
b = np.arange(3)

display(a)
display(b)

"""
1. Size of each array
 - a.shape = (2,3)
 - b.shape = (3,)
"""
print("==== Shape ====")
print(a.shape)
print(b.shape)
print("===============")

"""
2. follow rule number 1
 - a.shape = (2,3)
 - b.shape = (1,3)
 
3. follow rule number 2
 - a.shape = (2,3)
 - b.shape = (2,3)
"""

display(a + b)

array([[1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

==== Shape ====
(2, 3)
(3,)


array([[1., 2., 3.],
       [1., 2., 3.]])

In [15]:
vec1 = np.arange(3).reshape((3, 1))
vec2 = np.arange(3)

display(vec1)
display(vec2)

"""
1. Size of two arrays
 - vec1.shape = (3,1)
 - vec2.shape = (3,)
"""
print("==== Shape ====")
print(vec1.shape)
print(vec2.shape)
print("===============")

""" 
2. follow rule number 1
 - vec1.shape = (3,1)
 - vec2.shape = (1,3)
 
3. follow rule number 2
 - mat.shape = (3,3)
 - vec.shape = (3,3)
"""

display(vec1 + vec2)

array([[0],
       [1],
       [2]])

array([0, 1, 2])

==== Shape ====
(3, 1)
(3,)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [17]:
mat = np.ones((3, 2))
vec = np.arange(3)

display(mat)
display(vec)

"""
1. size of arrays
 - mat.shape = (3,2)
 - vec.shape = (3,)
"""

print("==== Shape ====")
print(mat.shape)
print(vec.shape)
print("==============")

""" 
2. follow rule number 1
 - mat.shape = (3,2)
 - vec.shape = (1,3)
 
3. follow rule number 2
 - mat.shape = (3,2)
 - vec.shape = (3,3)
"""

display(mat + vec)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([0, 1, 2])

==== Shape ====
(3, 2)
(3,)


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

### <span style="color:blue">**3. Broadcasting Examples**</span>

Normalizing array : in order to make the average of each column as 0

In [19]:
# (10,3) array
x = np.random.random((10, 3))

# average of each column
x_mean = x.mean(axis=0)

# normalize by broadcasting
x_cent = x - x_mean

display(x)
display(x_mean)
display(x_cent)
display(np.round(x_cent.sum(axis=0), 10))

array([[0.39001248, 0.8782508 , 0.85203452],
       [0.32846186, 0.47845973, 0.88001472],
       [0.81966597, 0.91033275, 0.10171476],
       [0.08771122, 0.38612884, 0.16702707],
       [0.90742477, 0.34171885, 0.64314906],
       [0.08647212, 0.86515529, 0.02334602],
       [0.14749921, 0.52559116, 0.76860794],
       [0.994018  , 0.71009453, 0.48180595],
       [0.18535889, 0.1038172 , 0.63231199],
       [0.95850903, 0.61302942, 0.95038178]])

array([0.49051335, 0.58125786, 0.55003938])

array([[-0.10050087,  0.29699294,  0.30199514],
       [-0.16205149, -0.10279813,  0.32997534],
       [ 0.32915261,  0.32907489, -0.44832463],
       [-0.40280213, -0.19512902, -0.38301231],
       [ 0.41691141, -0.23953901,  0.09310968],
       [-0.40404124,  0.28389744, -0.52669336],
       [-0.34301415, -0.05566669,  0.21856856],
       [ 0.50350465,  0.12883667, -0.06823343],
       [-0.30515446, -0.47744066,  0.08227261],
       [ 0.46799567,  0.03177156,  0.4003424 ]])

array([-0.,  0.,  0.])