In [1]:
import numpy as np
from IPython.display import display

## Question 1

Find a 10 by 10 array whose outer values equal 0 and inner values equal 1

In [7]:
arr = np.zeros((10, 10), dtype=int)
arr[1:-1, 1:-1] = 1
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Question 2

For array A and array B, calculate ((A+B) $\times$ (-A/2)) using in-place (without copy) method

In [47]:
A = np.array([[1,2], [4,5]], dtype=np.float32)
B = np.array([[3,5], [1,7]], dtype=np.float32)

#array B before calculation
display(B)

#calculation out-ing array B
display(np.dot(np.add(A, B), np.divide(-A, 2), out=B))

#display array B again
display(B)

array([[3., 5.],
       [1., 7.]], dtype=float32)

array([[-16. , -21.5],
       [-26.5, -35. ]], dtype=float32)

array([[-16. , -21.5],
       [-26.5, -35. ]], dtype=float32)

## Question 3

Given three arrays, create an array that satisfies the following conditions:
1. if cond[i] is true, select xarr[i]
2. if cond[i] is false, select yarr[i]
<br>
<br>
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])<br>
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])<br>
cond = np.array([True, False, True, True, False])

In [20]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

## Question 4

Given an array of size 11, change elements from the 5th index to the 9th index to negative numbers

In [48]:
#create an array
quiz4Arr = np.arange(11)
display(quiz4Arr)

#calculation
np.multiply(quiz4Arr[5:10], -1, out=quiz4Arr[5:10])

#display array
display(quiz4Arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 0,  1,  2,  3,  4, -5, -6, -7, -8, -9, 10])

## Question 5

Use random integer generator to create an array (size=20) whose values range from 0 to 9. Change the maximum value of the elements of this array to 0

In [4]:
arr = np.random.randint(0, 10, 20)
display(arr)

#use np.argsort to find the index of the sorted array
max_index = np.argsort(arr)[-1]

# #replace with zero
arr[max_index] = 0

display(arr)

array([5, 2, 6, 5, 6, 4, 7, 4, 5, 8, 2, 3, 6, 8, 6, 5, 1, 3, 5, 1])

array([5, 2, 6, 5, 6, 4, 7, 4, 5, 0, 2, 3, 6, 8, 6, 5, 1, 3, 5, 1])